language: ruby
rvm:
  - 1.9.3
env:
  - DB=sqlite
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - mysql -e 'create database tagglecloud_test'
  - psql -c 'create database tagglecloud_test' -U postgres